# Generated by Django 5.1.3 on 2024-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversation_options_conversation_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='bot_response',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
