# Generated by Django 5.1.3 on 2024-11-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_conversation_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, help_text="Title for the conversation, e.g., 'Chat about Symptoms'.", max_length=255, null=True),
        ),
    ]
