# Generated by Django 5.1.3 on 2024-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_generatedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_manually_renamed',
            field=models.BooleanField(default=False, help_text='Indicates if the title was manually renamed'),
        ),
    ]
