# Generated by Django 5.1.3 on 2024-12-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
