# Generated by Django 5.1.3 on 2024-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='collected_data',
            field=models.JSONField(default=dict),
        ),
    ]
