# Generated by Django 5.1.3 on 2024-12-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_conversation_current_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='current_step',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='collected_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores collected data like name, gender, age, medical history'),
        ),
    ]
