# Generated by Django 5.1.3 on 2024-12-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_conversation_questions_asked_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='collected_data',
        ),
        migrations.AddField(
            model_name='conversation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='medical_history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='questions_asked_count',
            field=models.IntegerField(default=0, help_text='Number of questions already asked'),
        ),
    ]
