# Generated by Django 5.1.3 on 2024-12-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_remove_conversation_collected_data_conversation_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='age',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='questions_asked_count',
        ),
    ]
